name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Check Python 3.12 on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install package
        run: python -m pip install -v .[test]

      - name: Test package
        run: pytest
        working-directory: examples
