name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    name: Check Python 3.12
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          allow-prereleases: true

      - name: Install package
        run: python -m pip install -v .[test]

      - name: Test package
        run: pytest
        working-directory: examples
